# [configuration_]
[configuration]
# Merge the per-attribute index arrays into a single index buffer. If disabled,
# the resulting mesh will be non-indexed, with vertex data duplicated according
# to per-attribute index arrays.
mergeIndexArrays=true
# [configuration_]
